CREATE DATABASE IF NOT EXISTS cruiser DEFAULT CHARACTER SET utf8mb4;

CREATE USER IF NOT EXISTS 'code_devops'@'%' IDENTIFIED BY 'ops-coffee';
GRANT ALL PRIVILEGES ON cruiser.* TO 'code_devops'@'%';
FLUSH PRIVILEGES;
